package aulajavaweb.model.enums;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public enum RacaCao {
	
	AFFENPINSCHER((byte) 1, "Affenpinscher"), 
	AFGHAN_HOUND((byte) 2, "Afghan Hound"), 
	AFRICANIS((byte) 3, "Africanis"), 
	AIDI((byte) 4, "Aidi"), 
	AIREDALE_TERRIER((byte) 5, "Airedale Terrier"),
	AKBASH((byte) 6, "Akbash"), 
	AKITA_AMERICANO((byte) 8, "Akita Americano"), 
	AKITA_INU((byte) 7, "Akita Inu"),
	ALAPAHA_BLUE_BLOOD_BULLDOG((byte) 9, "Alapaha Blue Blood Bulldog"), 
	ALASKAN_KLEE_KAI((byte) 10, "Alaskan Klee Kai"), 
	ALAUNT((byte) 11, "Alaunt"),
	AMERICAN_BULLY((byte) 12, "American Bully"),
	AMERICAN_PIT_BULL_TERRIER((byte) 13, "American Pit Bull Terrier"),
	AMERICAN_STAFFORDSHIRE_TERRIER((byte) 14, "American Staffordshire Terrier"), 
	ANGLO_FRANCES_DA_PEQUENA_VENERIE((byte) 15, "Anglo Francês da Pequena Venerie"), 
	APPENZELLER_SENNENHUND((byte) 16, "Staffordshire Bull Terrier"), 
	AZAWAKH((byte) 17, "Azawakh"),  
	BAKHARWAL((byte) 18, "Bakharwal"),  
	BANDOG((byte) 19, "Bandog"), 
	BARBET((byte) 20, "Barbet"), 
	BASENJI((byte) 21, "Basenji"),  
	BASSET_ARTESIANO_NORMANDO((byte) 22, "Basset Artesiano Normando"),  
	BASSET_AZUL_DA_GASCONHA((byte) 23, "Basset Azul da Gasconha"),  
	BASSET_DE_ARTOIS((byte) 24, "Basset de Artois"), 
	BASSET_FULVO_DA_BRETANHA((byte) 25, "Basset Fulvo da Bretanha"), 
	BASSET_HOUND((byte) 26, "Basset Hound"), 
	BEAGLE((byte) 27, "Beagle"),  
	BEARDED_COLLIE((byte) 28, "Bearded Collie"), 
	BEDLINGTON_TERRIER((byte) 29, "Bedlington Terrier"), 
	BICHON_BOLONHES((byte) 30, "Bichon Bolonhês"), 
	BICHON_DE_HAVANA((byte) 31, "Bichon de Havana"),  
	BICHON_FRISE((byte) 32, "Bichon Frisé"), 
	BICHON_HAVANES((byte) 33, "Bichon Havanês"),  
	BILLY((byte) 34, "Billy"), 
	BOERBOEL((byte) 35, "Boerboel"), 
	BOIADEIRO_AUSTRALIANO((byte) 36, "Boiadeiro Australiano"), 
	BOIADEIRO_AUSTRALIANO_DE_CAUDA_CHATA((byte) 37, "Boiadeiro Australiano de Cauda Chata"), 
	BOIADEIRO_DE_BERNA((byte) 38, "Boiadeiro de Berna"), 
	BOIEIRO_DAS_ARDENAS((byte) 39, "Boieiro das Ardenas"),  
	BOIEIRO_DAS_FLANDRES((byte) 40, "Boieiro das Flandres"),  
	BORDER_COLLIE((byte) 41, "Border Collie"), 
	BORDER_TERRIER((byte) 42, "Border Terrier"),  
	BORZOI((byte) 43, "Borzoi"), 
	BOSTON_TERRIER((byte) 44, "Boston Terrier"),  
	BOXER((byte) 45, "Boxer"), 
	BOYKIN_SPANIEL((byte) 46, "Boykin spaniel"), 
	BRACO_ALEMAO((byte) 47, "Braco Alemão"), 
	BRACO_DA_TRANSILVANIA((byte) 48, "Braco da Transilvânia"), 
	BRACO_DE_ARIEGE((byte) 49, "Braco de Ariege"),  
	BRACO_DE_AUVERNIA((byte) 50, "Braco de Auvérnia"), 
	BRACO_DE_BURBONIA((byte) 51, "Braco de Burbônia"),  
	BRACO_DINAMARQUÊS((byte) 52, "Braco Dinamarquês"),  
	BRACO_DUPUY((byte) 53, "Braco Dupuy"),  
	BRACO_ESLOVACO((byte) 54, "Braco Eslovaco"), 
	BRACO_FRANCES((byte) 55, "Braco Francês"), 
	BRACO_FRANCES_TIPO_GASCAO((byte) 56, "Braco Francês Tipo Gascão"), 
	BRACO_ITALIANO((byte) 57, "Braco Italiano"), 
	BRACO_POLONÊS((byte) 58, "Braco Polonês"), 
	BRACO_TIROLÊS((byte) 59, "Braco Tirolês"),  
	BUHUND_NORUEGUÊS((byte) 60, "Buhund Norueguês"),  
	BULDOGUE_AMERICANO((byte) 61, "Buldogue americano"),  
	BULDOGUE_AUSTRALIANO((byte) 62, " Buldogue Australiano"), 
	BULDOGUE_CAMPEIRO((byte) 63, "Buldogue campeiro"), 
	BULDOGUE_ESPANHOL((byte) 64, "Buldogue Espanhol"),  
	BULDOGUE_INGLES((byte) 65, "Buldogue Inglês"), 
	BULL_TERRIER((byte) 66, "Bull Terrier"), 
	BULLDOG((byte) 67, "Bulldog"), 
	BULLDOG_FRANCÊS((byte) 68, "Bulldog Francês"), 
	BULLENBEISSER((byte) 69, "Bullenbeisser"), 
	BULLMASTIFF_BRASILEIRO((byte) 70, "Bullmastiff Brasileiro"), 
	BULLY_KUTTA((byte) 71, "Bully Kutta"), 
	BULMASTIFE((byte) 72, "Bulmastife"), 
	CAIRN_TERRIER((byte) 73, "Cairn Terrier"), 
	CANE_CORSO((byte) 74, "Cane Corso"), 
	CAO_CANADENSE_ESQUIMO((byte) 75, "Cão Canadense Esquimó"),  
	CAO_CANADENSE_POINTER((byte) 76, "Cão Canadense Pointer"),  
	CÃO_CAROLINA((byte) 77, "Cão Carolina"), 
	CÃO_CHINÊS_DE_CHONGQING((byte) 78, "Cão Chinês de Chongqing"), 
	CÃO_DA_SERRA_DA_ESTRELA((byte) 79, "Cão da Serra da Estrela"),  
	CÃO_DA_SERRA_DE_AIRES((byte) 80, "Cão da Serra de Aires"), 
	CÃO_DÁGUA_ESPANHOL((byte) 81, " Cão d'água Espanhol"), 
	CÃO_DE_ÁGUA_PORTUGUÊS((byte) 82, "Cão d'água Português"),  
	CÃO_DE_APONTE_FRISÃO((byte) 83, "Cão de Aponte Frisão"), 
	CÃO_DE_APONTE_HERTHA((byte) 84, "Cão de Aponte Hertha"),
	CAO_DE_ARTOIS((byte) 85, "Cão de Artois"),  
	CÃO_DE_CAÇA_DA_POLÔNIA((byte) 86, "Cão de Caça da Polônia"),
	CÃO_DE_CANAÃ((byte) 87, "Cão de Canaã"),
	CÃO_DE_CASTRO_LABOREIRO((byte) 88, "Cão de Castro Laboreiro"),
	CÃO_DE_CRISTA_CHINÊS((byte) 89, "Cão de Crista Chinês"),
	CÃO_DE_GADO_TRANSMONTANO((byte) 90, "Cão de Gado Transmontano"),
	CÃO_DE_GUARDA_DE_MOSCOU((byte) 91, "Cão de Guarda de Moscou"), 
	CÃO_DE_GUARDA_HOLANDÊS((byte) 92, "Cão de Guarda Holandês"),
	CÃO_DE_KANGAL((byte) 93, "Cão de Kangal"), 
	CÃO_DE_MONTANHA_DOS_PIRENÉUS((byte) 94, "Cão de Montanha dos Pirenéus"), 
	CÃO_DE_PRESA_MAIORQUINO((byte) 95, "Cão de Presa Maiorquino"), 
	CÃO_DE_SANTO_HUMBERTO((byte) 96, "Cão de Santo Humberto"), 
	CÃO_DE_TAIWAN((byte) 97, "Cão de Taiwan"), 
	CÃO_DE_URSOS_DA_CARÉLIA((byte) 98, "Cão de Ursos da Carélia"), 
	CÃO_DO_ARIEGE((byte) 99, "Cão do Ariége"),
	CÃO_FAREJADOR_DE_HANÔVER((byte) 100, "Cão Farejador de Hanôver"), 
	CÃO_FILA_DE_SÃO_MIGUEL((byte) 101, "Cão Fila de Sâo Miguel"), 
	CÃO_FRANCÊS((byte) 102, "Câo Francês"), 
	CÃO_LUTADOR_DA_CÓRDOBA((byte) 103, "Cão Luatado de Córdoba"),  
	CÃO_PASTOR_DE_ARMANT((byte) 104, "Cão Pastor de Armant "), 
	CATAHOULA_CUR((byte) 105, "Catahoula Cur"), 
	CAVALIER_KING_CHARLES_SPANIEL((byte) 106, "Cavalier King Charles Spaniel"),  
	CHIHUAHUA((byte) 107, "Chihuahua"), 
	CHINOOK((byte) 108, "Chinook"), 
	CHIPPIPARAI((byte) 109, "Chippiparai"),  
	CHORTAJ((byte) 110, "Chortaj"), 
	CHOW_CHOW((byte) 111, "Chow-chow"),  
	CIMARRON_URUGUAYO((byte) 112, "Cimarron Uruguaio"),  
	CIRNECO_DO_ETNA((byte) 113, "Cinerco do Etna"), 
	CLUMBER_SPANIEL((byte) 114, "Clumber Spaniel"),  
	COATED_RETRIEVER((byte) 115, "Coated Retriever"),  
	COCKER_SPANIEL_AMERICANO((byte) 116, "Cocker Spaniel Americano"), 
	COCKER_SPANIEL_INGLÊS((byte) 117, "Cocker Spaniel Inglês"),
	COCKERPOO((byte) 118, "Cockerpoo"),  
	COLLIE_ESCOCÊS((byte) 119, "Collie Escocês"),
	COMBAI((byte) 120, "Combai"),
	COOLIE_AUSTRALIANO((byte) 121, "Coolie Australiano"),
	COONHOUND_DE_PINTAS_AZUIS((byte) 122, "Coonhound de Pintas Azuis"), 
	COONHOUND_INGLÊS((byte) 123, "Coonhound Inglês"),
	COONHOUND_PRETO_E_CASTANHO((byte) 124, "Coonhound Preto e Castanho"),
	COONHOUND_WALKER_TREEING((byte) 125, "Coonhound Walker Treeing"),
	COTON_DE_TULEAR((byte) 126, "Coton de Tulear"),
	CUR_FULVO_DE_FOCINHO_PRETO((byte) 127, "Cur Fulvo de Focinho Preto"),
	CUR_MONTANHÊS((byte) 128, "Cur Montanhês"), 
	CURLY_COATED_RETRIEVER((byte) 129, "Curly Coated Retriever"),
	CUVAC_ESLOVACO((byte) 130, "Cuvac Eslovaco"),
	DACHSHUND((byte) 131, "Dachshund"),
	DÁLMATA((byte) 132, "Dálmata"), 
	DANDIE_DINMONT_TERRIER((byte) 133, "Dandie Dinmont Terrier"),
	DANISH_SWEDISH_FARMDOG((byte) 134, "Danish Swedish Farmdog"), 
	DEERHOUND((byte) 135, "Deerhound"), 
	DENMARK_MASTIFF((byte) 136, "Denmark Mastiff"), 
	DOBERMANN((byte) 137, "Dobermann"),
	DOGO_ARGENTINO((byte) 138, "Dogo Argentino"),
	DOGO_CANARIO((byte) 139, "Dogo Canario"),
	DOGO_SARDESCO((byte) 140, "Dogo Sardesco"),
	DOGUE_ALEMÃO((byte) 141, "Dogue Alemão"), 
	DOGUE_BRASILEIRO((byte) 142, "Dogue Brasileiro"),
	DOGUE_DE_BORDEAUX((byte) 143, "Dogue de Bordeaux"),  
	DUTCH_PARTRIDGE_DOG((byte) 144, "Dutch Partridge Dog"), 
	EAST_EUROPEAN_SHEPHERD((byte) 145, "East European Shepherd"), 
	EAST_SIBERIAN_LAIKA((byte) 146, "East Siberian Laika"),
	EGYPTIAN_SHEEPDOG((byte) 147, "Egyptyan Sheepdog"),
	ELKHOUND_NORUEGUÊS_CINZA((byte) 148, "Elkhound Norueguês Cinza"),
	ELKHOUND_NORUEGUÊS_PRETO((byte) 149, "Elkhound Norueguês Preto"),
	ENGLISH_TOY_TERRIER((byte) 150, "English Toy Terrier"),
	ETOPO((byte) 151, "Etopo"), 
	FAWN_BRITTANY_GRIFFON((byte) 152, "Fawn Brittany Griffon"), 
	FIELD_SPANIEL((byte) 153, "Field Spaniel"),
	FILA_BRASILEIRO((byte) 154, "Fila Brasileiro"),  
	FINNISH_HOUND((byte) 155, "Finnish Hound"),
	FINNISH_SPITZ((byte) 156, "Finnish Spitz"), 
	FLAT_COATED_RETRIEVER((byte) 157, "Flat Coated Retriever"),
	FOX_TERRIER((byte) 158, "Fox Terrier"),
	FOX_TERRIER_PELO_DURO((byte) 159, "Fox Terrier de Pelo Duro"), 
	FOXHOUND_AMERICANO((byte) 160, "Foxhound Americano"), 
	FOXHOUND_INGLÊS((byte) 161, "Foxhound Inglês"),
	FRENCH_POINTING_DOG_GASCOGN((byte) 162, "French Pointing Dog Gascogn"),
	FRENCH_POINTING_DOG_PYRENEAN((byte) 163, "French Pointing Dog Pyrenean"), 
	FRENCH_WATER_DOG((byte) 164, "French Water Dog"),
	FTOPO((byte) 165, "Ftopo"), 
	GALGO_ESPANHOL((byte) 166, "Galgo Espanhol"),
	GASCÃO_DE_SAINTONGEOIS((byte) 167, "Gascão de Saintongeois"), 
	GERMAN_HOUND((byte) 168, "German Hound"),
	GERMAN_LONGHAIRED_POINTER((byte) 169, "German Longhaired Pointer"),
	GERMAN_PINSCHER((byte) 170, "German Pinscher"),
	GERMAN_ROUGH_HAIRED_POINTING_DOG((byte) 171, "German Rough Haired Pointing Dog"),
	GERMAN_SPANIEL((byte) 172, "German Spaniel"),
	GOLDEN_RETRIEVER((byte) 173, "Golden Retriever"), 
	GRAND_ANGLO_FRANCAIS_TRICOLORE_HOUND((byte) 174, "Grand Anglo Francais Tricolore Hound"),
	GRAND_BASSET((byte) 175, "Grand Basset"), 
	GRANDE_AZUL_DA_GASCONHA((byte) 176, "Grande Azul da Gasconha"),
	GRANDE_MUNSTERLANDER((byte) 177, "Grande Munsterlander"),
	GREAT_ANGLO_FRANCAIS_WHITE_AND_BLACK_HOUND((byte) 178, "Great Anglo Francais White and Black Hound"),
	GREATER_SWISS_MOUNTAIN_DOG((byte) 179, "Greater Swiss Mountain Dog"), 
	GREYHOUND((byte) 180, "Greyhound"),
	GRIFFON_BELGA((byte) 181, "Griffon Belga"),
	GRIFFON_BLEU_DE_GASCOGNE((byte) 182, "Griffon Bleu de Gascogne"),
	GRIFFON_DE_APONTE_DE_PELO_DURO_KORTHALS((byte) 183, "Griffon de Aponte de Pelo Duro Korthals"),
	GRIFFON_DE_BRUXELAS((byte) 184, "Griffon de Bruxelas"),
	GRIFFON_DE_CAÇA_CHECO((byte) 185, "Griffon de Caça Checo"), 
	GRIFFON_NIVERNAIS((byte) 186, "Griffon Nivernais"),
	GRIFFON_VENDÉEN((byte) 187, "Griffon Vendéen"),
	GTOPO((byte) 188, "Gtopo"),
	GUATEMALA_N_BULL_TERRIER((byte) 189, "Guatemala Bull Terrier"),
	HALDEN_HOUND((byte) 190, "Halden Hound"),
	HANOVER_HOUND((byte) 191, "Hanover Hound"),
	HARRIER((byte) 192, "Harrier"), 
	HELLENIC_HOUND((byte) 193, "Hellenic Hound"),
	HOKKAIDO((byte) 194, "Hokkaido"), 
	HORTAYA_BORZAYA((byte) 195, "Hortaya Borzaya"),
	HOVAWART((byte) 196, "Hovawart"), 
	HTOPO((byte) 197, "Htopo"),
	HUNGARIAN_GREYHOUND((byte) 198, "Hungarian Greyhound"),
	HUNGARIAN_HOUND((byte) 199, "Hungarian Hound"),
	HUSKY_SIBERIANO((byte) 200, "Husky Siberiano"),
	HYGENHUND((byte) 201, "Hygenhund"),
	ICELANDIC_SHEEPDOG((byte) 202, "Icelandic Sheepdog"),
	INDIAN_BEAR_HOUND((byte) 203, "Indian Bear Hound"),
	INDIAN_MASTIFF((byte) 204, "Indian Mastiff"),
	IRISH_SOFT_COATED((byte) 205, "Irish Soft Coated"),
	ISTRIAN_COARSE_HAIRED_HOUND((byte) 206, "Istrian Coarse Haired Hound"), 
	ITALIAN_HOUND((byte) 207, "Italian Hound"), 
	ITOPO((byte) 208, "Itopo"),
	JACK_RUSSEL_TERRIER((byte) 209, "Jack Russel Terrier"), 
	JAPANESE_TERRIER((byte) 210, "Japanese Terrier"),  
	JONANGI((byte) 211, "Jonangi"), 
	JTOPO((byte) 212, "Jtopo"), 
	KAI_KEN((byte) 213, "Kai Ken"),  
	KARAKACHAN_DOG((byte) 214, "Karakachan Dog"), 
	KARELIAN_BEAR_DOG((byte) 215, "Karelian Bear Dog"), 
	KARST_SHEPHERD((byte) 216, "Karst Shepherd"), 
	KASHMIR_SHEEPDOG((byte) 217, "Kashmir Sheepdog"),  
	KEESHOND((byte) 218, "Keeshond"), 
	KERRY_BLUE_TERRIER((byte) 219, "Kerry Blue Terrier"), 
	KING_CHARLES_SPANIEL((byte) 220, "King Charles Spaniel"), 
	KINTAMANI((byte) 221, "Kintamani"),
	KISHU((byte) 222, "Kishu"),
	KOMONDOR((byte) 223, "Komondor"),
	KOOIKER_HOUND((byte) 224, "Kooiker Hound"),
	KOREAN_JINDO_DOG((byte) 225, "Korean Jindo Dog"),
	KROMFOHRLANDER((byte) 226, "Kromfohrlander"),
	KTOPO((byte) 227, "Ktopo"), 
	KUVASZ((byte) 228, "Kuvasz"),
	KYI_LEO((byte) 229, "Kyi Leo"), 
	LAGOTTO_ROMAGNOLOKYI_LEO((byte) 230, "Lagotto Romagnolokyi Leo"), 
	LAIKA((byte) 231, "Laika"), 
	LAKELAND_TERRIERKYI_LEO((byte) 232, "Lakeland Terrierkyi Leo"), 
	LANCASHIRE_HEELERKYI_LEO((byte) 233, "Lancashire Heelerkyi Leo"), 
	LANDSEERKYI_LEO((byte) 234, "Landserrkyi Leo"),  
	LAPPONIAN_HERDERKYI_LEO((byte) 235, "Lapponian Herderkyi Leo"), 
	LARGE_VENDÉEN_GRIFFONKYI_LEO((byte) 236, "Large Vendéen Griffonkyi Leo"),  
	LEONBERGER((byte) 237, "Leonberger"),  
	LHASA_APSO((byte) 238, "Lhasa Apso"),  
	LITHUANIAN_HOUND((byte) 239, "Lithuanian Hound"),   
	LTOPOKYI_LEO((byte) 240, "Ltopokyi Leo"), 
	MAJORCA_SHEPHERD_DOG((byte) 241, "Majorca Shepherd Dog"),  
	MALAMUTE_DO_ALASKA((byte) 242, "Malamute do Alaska"),
	MALLORQUIN_MASTIFF((byte) 243, "Mallorquin Mastiff"),
	MALTÊS((byte) 244, "Maltês"), 
	MANCHESTER_TERRIER((byte) 245, "Manchester Terrier"),
	MASTIFF((byte) 246, "Mastiff"),
	MASTIFF_AMERICANO((byte) 247, "Matiff Americano"),
	MASTIFF_TIBETANO((byte) 248, "Mastiff Tibetano"), 
	MASTIM_DOS_PIRINEUS((byte) 249, "Mastim dos Pirineus"), 
	MASTIM_ESPANHOL((byte) 250, "Mastim Espanhol"),
	MASTINO_NAPOLETANO((byte) 251, "Manstino Napoletano"),
	MEDIUM_SIZED_ANGLO_FRENCH_HOUND((byte) 252, "Medium-sized Aglo French Hound"),
	MEDIUM_VENDÉEN_GRIFFON((byte) 253, "Medium Vendéen Griffon"), 
	MONTENEGRIN_MOUNTAIN_HOUND((byte) 254, "Mantenegrin Mountain Dog"), 
	MOSCOW_WATCHDOG((byte) 255, "Moscow Watchdog"), 
	MTOPO((byte) 256, "Mtopo"),  
	MUCUCHIES((byte) 257, "Mucuchies"), 
	MUDHOL_HOUND((byte) 258, "Mudhol Hound"), 
	MUDI((byte) 259, "Mudi"),  
	MURRAY_RIVER_CURLY((byte) 260, "Murray River Curly"),  
	NAVARRO_POINTER((byte) 261, "Navarro Pointer"),
	NEW_GUINEA_SINGING_DOG((byte) 262, "New Guinea Singing Dog"),
	NEW_ZEALAND_SHEEPDOG((byte) 263, "New Zealand Sheepdog"),
	NORDIC_SPITZ((byte) 264, "Nordic Spitz"),
	NORFOLK_TERRIER((byte) 265, "Norfolk Terrier"),
	NORTH_INDIAN_GREYHOUND((byte) 266, "North Indian Greyhound"), 
	NORWEGIAN_BUHUND((byte) 267, "Norwegian Buhund"),
	NORWEGIAN_HOUND((byte) 268, "Norwegian Hound"),
	NORWEGIAN_LUNDEHUND((byte) 269, "Norwegian Lunderhound"),
	NTOPO((byte) 270, "Ntopo"),
	OLD_DANISH_POINTER((byte) 271, "Old Danish Pointer"),
	OLD_ENGLISH_SHEEPDOG((byte) 272, "Old English Sheepdog"),  
	ORWICH_TERRIER((byte) 273, "Orwich Terrier"),
	OTTERHOUND((byte) 274, "Otterhound"),  
	OVELHEIRO_GAÚCHO((byte) 275, "Ovelheiro Gaúcho"), 
	PAKISTAN_BULL_DOG((byte) 276, "Pakistan Bull Dog"), 
	PARSON_RUSSELL_TERRIER((byte) 277, ""),
	PASTOR_ALEMÃO((byte) 278, "Pastor Alemão"),  
	PASTOR_BELGA_GROENENDAEL((byte) 279, "Pastor Belga Groenendael"), 
	PASTOR_BELGA_LAEKENOIS((byte) 280, "Pastor Belga Laekenois"),
	PASTOR_BELGA_MALINOIS((byte) 281, "Pastor Belga Malinois"),
	PASTOR_BELGA_TERVUREN((byte) 282, "Pastor Belga Tervuren"),
	PASTOR_BERGAMASCO((byte) 283, "Pastor Bergamasco"),
	PASTOR_BRANCO_SUIÇO((byte) 284, "Pastor Branco Suiço"),
	PASTOR_CROATA((byte) 285, "Pastor Croata"), 
	PASTOR_DA_ANATÓLIA((byte) 286, "Pastor da Anatólia"),
	PASTOR_DA_ÁSIA_CENTRAL((byte) 287, "Pastor da Ásia Central"),
	PASTOR_DE_BEAUCE((byte) 288, "Pastor de Beauce"),
	PASTOR_DE_BRIE((byte) 289, "Pastor de Brie"),
	PASTOR_DE_SHETLAND((byte) 290, "Pastor de Shetland"),
	PASTOR_DO_CÁUCASO((byte) 291, "Pastor do Cáucaso"),
	PASTOR_FINLANDÊS_DA_LAPÔNIA((byte) 292, "Pastor Finlandês da Lapônia"),
	PASTOR_HOLANDÊS((byte) 293, "Pastor Holandês"),
	PASTOR_MAREMANO_ABRUZÊS((byte) 294, "Pastor Maremano Abruzês"), 
	PASTOR_POLONÊS_DA_PLANÍCIE((byte) 295, "Pastor Polonês da Planície"),
	PATTERDALE_TERRIER((byte) 296, "Patterdale Terrier"),  
	PELADO_MEXICANO((byte) 297, "Pelado Mexicano"), 
	PELADO_PERUANO((byte) 298, "Pelado Peruano"), 
	PEQUENÊS((byte) 299, "Pequenês"), 
	PEQUENO_CÃO_LEÃO((byte) 300, "Pequeno Cão Leão"), 
	PEQUENO_LEBREL_ITALIANO((byte) 301, "Pequeno Lebrel Italiano"), 
	PEQUENO_SABUJO_SUICO((byte) 302, "Pequeno Sabujo Suíço"), 
	PEQUENO_SPANIEL_CONTINENTAL((byte) 303, "Pequeno Spaniel Continetal"), 
	PERDIGUEIRO_PORTUGUÊS((byte) 304, "Perdigueiro Português"),
	PETIT_BASSET_GRIFFON_VENDÉEN((byte) 305, "Petit Basset Griffon Vendéen"), 
	PETIT_BLEU_DE_GASCOGNE((byte) 306, "Petit Belu de Gascogne"),
	PETIT_RABANÇON((byte) 325, "Petit Rabaçon"),
	PHARAOH_HOUND((byte) 326, "Pharaoh Hound"),
	PINSCHER((byte) 327, "Pinscher"),  
	PINSCHER_MINIATURA((byte) 328, "Pinscher Miniatura"), 
	PIT_BULL((byte) 329, "Pit Bull"),
	PLOTT_HOUND((byte) 330, "Plott Hound"), 
	PODENGO_CANARIO((byte) 331, "Podengo Canario"), 
	PODENGO_IBICENCO((byte) 332, "Podengo Ibicenco"), 
	PODENGO_PORTUGUÊS((byte) 333, "Podengo Português"),
	POINTER_INGLÊS((byte) 334, "Pointer Inglês"), 
	POITEVIN((byte) 335, "Poitevin"), 
	POLISH_GREYHOUND((byte) 334, "Polish Greyhound"), 
	POLISH_HOUND((byte) 335, "Polish Hound"), 
	POLISH_HUNTING_DOG((byte) 336, "Polish Hunting Dog"), 
	POLISH_TATRA_SHEEPDOG((byte) 337, "Polish Tatra Sheepdog"), 
	POMERANIAN((byte) 338, "Pomeranian"), 
	PONT_AUDEMER_SPANIEL((byte) 339, "Pont Audemer Spaniel"), 
	POODLE((byte) 340, "Poodle"), 
	POODLE_STANDARD((byte) 341, "Poodle Standard"), 
	PORCELAINE((byte) 342, "Porcelaine"), 
	POSAVAZ_HOUND((byte) 343, "Posavaz Hound"), 
	PRAGUE_RATTER((byte) 344, "Prague Ratter"), 
	PTOPO((byte) 345, "Ptopo"), 
	PUDELPOINTER((byte) 346, "Pudelpointer"), 
	PUG((byte) 347, "Pug"),
	PULI((byte) 348, "Puli"),
	PUMI((byte) 349, "Pumi"),
	PUNGSAN_DOG((byte) 350, "Pungsan Dog"),
	PYRENEAN_SHEEPDOG((byte) 351, "Pyrenean Sheepdog"),
	RAFEIRO_DO_ALENTEJO((byte) 352, "Rafeiro do Alentejo"),
	RAJAPALAYAM_HOUND((byte) 353, "Rajapalayam Hound"), 
	RAT_TERRIER((byte) 354, "Rat Terrier"), 
	REDBONE_COONHOUND((byte) 355, ""), 
	RETRIEVER_DA_NOVA_ESCÓCIA_DUCK_TOLLING((byte) 356, "Retriever da Nova Escócia Duck Tolling"),
	RETRIEVER_DO_LABRADOR((byte) 357, "Retriever do Labrador"),
	RHODESIAN_RIDGEBACK((byte) 358, "Rhodesian Ridgeback"),
	ROMANIAN_CARPATHIAN_SHEPHERD((byte) 359, "Romanian Carpathian Shepherd"), 
	ROMANIAN_MIORITIC_SHEPHERD((byte) 360, "Romanian Mioritic Shepherd"),
	ROTTWEILER((byte) 361, "Rottweiler"), 
	RTOPO((byte) 362, "Rtopo"),
	RUSSIAN_EUROPEAN((byte) 363, "Russian European"), 
	RUSSIAN_TOY((byte) 364, "Russian Toy"),  
	SAARLOOSWOLFHOND((byte) 365, "Saarlooswolfhound"),
	SABUJO_DA_ÍSTRIA_DE_PELO_CURTO((byte) 366, "Sabujo da Ístria de Pelo Curto"), 
	SABUJO_FRANCÊS_BRANCO_E_LARANJA((byte) 367, "Sabujo Francês Banco e Laranja"),
	SABUJO_FRANCÊS_BRANCO_E_PRETO((byte) 368, "Sabujo Francês Preto e Branco"),
	SABUJO_FRANCÊS_TRICOLOR((byte) 369, "Sabujo Francês Tricolor"),
	SABUJO_MONTANHÊS_DA_BAVIERA((byte) 370, "Sabujo Montanhês da Baviera"),  
	SALUKI((byte) 371, "Saluki"), 
	SAMOIEDA((byte) 372, "Samoieda"),
	SÃO_BERNARDO((byte) 373, "São Bernardo"),   
	SAPSALI((byte) 374, "Sapsali"),
	SCHAPENDOES((byte) 375, "Schapendoes"),
	SCHILLER_HOUND((byte) 376, "Schiller Hound"),
	SCHIPPERKE((byte) 377, "Schipperke"), 
	SCHNAUZER((byte) 378, "Schnauzer"), 
	SCHNAUZER_GIGANTE((byte) 379, "Schnauzer Gigante"),
	SCHNAUZER_MINIATURA((byte) 377, "Schnauzer Miniatura"), 
	SCHWEIZER_LAUFHUND((byte) 378, "Schweizer Laufhund"), 
	SEALYHAM_TERRIER((byte) 379, "Sealyham Terrier"), 
	SERBIAN_HOUND((byte) 380, "Serbian Hound"),  
	SERBIAN_TRICOLOUR_HOUND((byte) 381, "Serbian Tricolour Hound"),  
	SETTER_GORDON((byte) 382, "Setter Gordon"),  
	SETTER_INGLÊS((byte) 383, "Setter Inglês"),  
	SETTER_IRLANDÊS_RUIVO((byte) 384, "Setter Irlandês Ruivo"),  
	SETTER_IRLANDÊS_VERMELHO_E_BRANCO((byte) 385, "Setter Irlandês Vermelho e Branco"),  
	SHAR_PEI((byte) 386, "Shar Pei"),  
	SHIBA((byte) 387, "Shiba"),  
	SHIH_TZU((byte) 388, "Shih Tzu"), 
	SHIKOKU((byte) 389, "Shikoku"),  
	SHILOH_SHEPHERD((byte) 390, "Shiloh Shepherd"),  
	SILKEN_WINDHOUND((byte) 391, "Silken Windhound"),  
	SILKY_TERRIER_AUSTRALIANO((byte) 392, "Silky Terrier Australiano"), 
	SKYE_TERRIER((byte) 393, "Skye Terrier"), 
	SLOVAK_CUVAC((byte) 394, "Slovak Cuvac"),  
	SLOVAKIAN_HOUND((byte) 395, "Slovakian Hound"), 
	SLOVAKIAN_WIREHAIRED_POINTING_DOG((byte) 396, "Slovakian Wirehaired Pointing Dog"), 
	SMAL_MUNSTERLANDER((byte) 397, "Smal Munsterlander"),  
	SMALAND_HOUND((byte) 398, "Smalan Hound"), 
	SMALL_BERNESE_HOUND((byte) 399, "Small Bernese Hound"), 
	SMALL_SWISS_HOUND((byte) 400, "Small Swiss Hound"),  
	SMOUSHOND_HOLANDÊS((byte) 401, "Smoushond Holandês"), 
	SOUTH_RUSSIAN_OVCHARKA((byte) 402, "South Russian Ovcharka"),  
	SPANIEL_BRETÃO((byte) 403, "Spaniel Bretão"), 
	SPANIEL_DA_PICARDIA((byte) 404, "Spaniel da Picardia"), 
	SPANIEL_DÁGUA_AMERICANO((byte) 405, "Spaniel D´água Americano"), 
	SPANIEL_DÁGUA_IRLANDÊS((byte) 406, "Spaniel D´água Irlandês"), 
	SPANIEL_FRANCÊS((byte) 407, "Spaniel Francês"), 
	SPANIEL_JAPONÊS((byte) 408, "Spaniel Japonês"), 
	SPANIEL_TIBETANO((byte) 409, "Spaniel Tibetano"),
	SPANISH_SCENTHOUND((byte) 410, "Spanish Scenthound"), 
	SPANISH_WATER_DOG((byte) 411, "Spanish Water Dog"), 
	SPINONE_ITALIANO((byte) 412, "Spinone Italiano"), 
	SPITZ_ALEMÃO((byte) 413, "Spitz Alemão"), 
	SPITZ_JAPONÊS((byte) 414, "Spitz Japonês"),  
	SPRINGER_SPANIEL_INGLÊS((byte) 415, "Springer Spaniel Inglês"), 
	SRD_VIRALATA((byte) 416, "Sem Raça Definida"), 
	ST_GERMAIN_POINTING_DOG((byte) 417, "St. Germain Pointing Dog"), 
	STABYHOUN((byte) 418, "Stabyhoun"),   
	STAFFORDSHIRE_BULL_TERRIER((byte) 419, "Staffordshire Bull Terrier"), 
	STOPO((byte) 420, "Stopo"),
	STYRIAN_COARSE_HAIRED_HOUND((byte) 421, "Styrian Coarse Haired Hound"), 
	SUSSEX_SPANIEL((byte) 422, "Sussex Spaniel"), 
	SWEDISH_DACHSBRACKE((byte) 423, "Swedish Dachbracke"), 
	SWEDISH_ELKHOUND((byte) 424, "Swedish Elkhound"), 
	SWEDISH_FOXHOUND((byte) 425, "Swedish Foxhound"), 
	SWEDISH_LAPPHUND((byte) 426, "Swedish Lapphund"),  
	SWEDISH_VALLHUND((byte) 427, "Swedish Vallhund"),   
	TAIGAN((byte) 428, "Taigan"),   
	TAIWAN_DOG((byte) 429, "Taiwan Dog"),  
	TAMASKAN_DOG((byte) 430, "Tamaskan Dog"),  
	TENTERFIELD_TERRIER((byte) 431, "Tenterfield Terrier"),  
	TERRA_NOVA((byte) 432, "Terra Nova"),   
	TERRIER_ALEMÃO_DE_CAÇA((byte) 432, "Terrier Alemão de Caça"),  
	TERRIER_AMERICANO_SEM_PELO((byte) 433, "Terrier Alemão sem Pelo"),  
	TERRIER_BRASILEIRO((byte) 434, "Terrier Brasileiro"),  
	TERRIER_ESCOCÊS((byte) 435, "Terrier Escocês"),  
	TERRIER_IRLANDÊS((byte) 436, "Terrier Irlandês"),   
	TERRIER_IRLANDÊS_DO_GLEN_DO_IMAAL((byte) 437, "Terrier Irlandês do Glen do Imaal"),  
	TERRIER_PRETO_DA_RÚSSIA((byte) 438, "Terrier Preto da Rússia"),  
	TERRIER_TIBETANO((byte) 439, "Terrier Tibetano"),  
	THAI_BANGKAEW_DOG((byte) 440, "Thai Bangkaew Dog"),  
	THAI_RIDGEBACK_DOG((byte) 441, "Thai Ridgeback Dog"),   
	TOPO((byte) 442, "Topo"),
	TOSA((byte) 443, "Tosa"),  
	TOY_FOX_TERRIER((byte) 444, "Toy Fox Terrier"),  
	TOY_MANCHESTER_TERRIER((byte) 445, "Toy Manchester Terrier"),  
	TREEING_TENNESSEE_BRINDLE((byte) 446, "Treeing Tennesee Brindle"),  
	TREEING_WALKER_COONHOUND((byte) 447, "Treeing Walker Coonhound"),  
	TTOPO((byte) 448, "Ttopo"),  
	TURKISH_SHEPHERD_DOG((byte) 449, "Turkish Shepherd Dog"),  
	TYROLEAN_HOUND((byte) 450, "Tyrolean Hound"),  
	VEADEIRO_PAMPEANO((byte) 451, "Veadeiro Pampeano"),  
	VOLPINO_ITALIANO((byte) 452, "Volpino Italiano"), 
	VTOPO((byte) 453, "Vtopo"),  
	WEIMARANER((byte) 454, "Weimaraner"), 
	WELSH_CORGI_CARDIGAN((byte) 455, "Welsh Corgi Cardigan"), 
	WELSH_CORGI_PEMBROKE((byte) 456, "Welsh Corgi Pembroke"),  
	WELSH_SPRINGER_SPANIEL((byte) 457, "Welsh Springer Spaniel"), 
	WELSH_TERRIER((byte) 458, "Welsh Terrier"),  
	WEST_HIGHLAND_WHITE_TERRIER((byte) 459, "West Highland White Terrier"),  
	WEST_SIBERIAN_LAIKA((byte) 460, "West Siberian Laika"),  
	WESTPHALIAN_HOUND((byte) 461, "Westphalian Hound"), 
	WETTERHOUN((byte) 462, "Wetterhoun"),  
	WHEATEN_TERRIER((byte) 463, "Wheaten Terrier"), 
	WHIPPET((byte) 464, "Whippet"),  
	WOLFHOUND_IRLANDÊS((byte) 465, "Wolfhound Irlandês"), 
	WTOPO((byte) 466, "Wtopo"),  
	YORKSHIRE_TERRIER((byte) 467, "Yorkshire Terrier"), 
	YTOPO((byte) 468, "Ytopo");  

	
	private byte code;
	private String description;
	
	private RacaCao(byte code, String description) {
		this.code = code;
		this.description = description;
	}
	
	public byte getCode() {
		return code;
	}
	
	public String getDescription() {
		return description;
	}
	
	public RacaCao getByCode(byte code) {
		for(RacaCao r : values()) {
			if(r.code == code) return r; 
		}
		return null;
	}
	
	public RacaCao getByDescription(String description) {
		for(RacaCao r : values()) {
			if(r.description.equalsIgnoreCase(description)) return r;
		}
		return null;
	}
	
	
	
	
}


